
import 'react-loading-skeleton/dist/skeleton.css'
import "./globals.css"
import 'bootstrap/dist/css/bootstrap.min.css';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/03244eb91d.js" crossOrigin="anonymous"></script>
      </head>
      <body >{children}</body>
    </html>
  )
}
